version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 2.2
  build:
    commands:
      - dotnet restore WikiGameBot/WikiGameBot.csproj
      - dotnet build WikiGameBot/WikiGameBot.csproj
      - dotnet publish WikiGameBot/WikiGameBot.csproj -o ./staging/app -r linux-x64 --self-contained true
artifacts:
  files:
    - '**/*'
