// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WikiGameBot.Data;

namespace WikiGameBot.Data.Migrations
{
    [DbContext(typeof(WikiBotDataDbContext))]
    [Migration("20190822170550_AddingGameStartAndEndPoints")]
    partial class AddingGameStartAndEndPoints
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WikiGameBot.Data.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EndingUrl");

                    b.Property<bool>("IsActive");

                    b.Property<string>("StartingUrl");

                    b.Property<DateTime>("ThreadTimeStamp");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WikiGameBot.Data.Entities.GameEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId");

                    b.Property<int>("LinkCount");

                    b.Property<string>("RawText");

                    b.Property<string>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("GameEntries");
                });

            modelBuilder.Entity("WikiGameBot.Data.Entities.Player", b =>
                {
                    b.Property<string>("SlackUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NumberOfEntries");

                    b.Property<int>("NumberOfWins");

                    b.Property<string>("SlackUserName");

                    b.HasKey("SlackUserId");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
